version: '2'
services:
  nginx:
    image: aloo/bedrock-nginx:latest
    ports:
     - "8000:80"
    volumes:
     - ./bedrock:/usr/share/nginx/html
    links:
     - wordpress_db
  php:
    image: aloo/bedrock-php:latest
    volumes:
     - ./bedrock:/usr/share/nginx/html
  wordpress_db:
    image: mariadb
    environment:
        MYSQL_ROOT_PASSWORD: secret
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - wordpress_db:db
    ports:
      - 8181:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: secret
volumes:
  data:
    driver: "local"